import type { Employee, Customer, InventoryItem, WorkOrder, Invoice, QuoteHistoryEntry, InvoiceHistoryEntry, User } from "../../../types";

/**
 * Get employee name by ID
 * @param id - Employee ID
 * @param employees - Array of employees
 * @returns Employee name or "Onbekend" if not found
 */
export const getEmployeeName = (id: string, employees: Employee[]): string => {
  return employees.find((e) => e.id === id)?.name || "Onbekend";
};

/**
 * Get customer name by ID
 * @param customerId - Customer ID
 * @param customers - Array of customers
 * @returns Customer name or "Onbekend" if not found
 */
export const getCustomerName = (customerId: string, customers: Customer[]): string => {
  return customers.find((c) => c.id === customerId)?.name || "Onbekend";
};

/**
 * Get inventory item name by ID
 * @param itemId - Inventory item ID
 * @param inventory - Array of inventory items
 * @returns Inventory item name or "Onbekend item" if not found
 */
export const getInventoryItemName = (itemId: string, inventory: InventoryItem[]): string => {
  return inventory.find((i) => i.id === itemId)?.name || "Onbekend item";
};

/**
 * Get Tailwind CSS classes for quote status badge
 * @param status - Quote status
 * @returns Tailwind CSS classes string
 */
export const getQuoteStatusColor = (status: string): string => {
  switch (status) {
    case "approved":
      return "bg-green-100 text-green-800";
    case "sent":
      return "bg-blue-100 text-blue-800";
    case "rejected":
      return "bg-red-100 text-red-800";
    case "expired":
      return "bg-gray-100 text-gray-800";
    case "draft":
      return "bg-yellow-100 text-yellow-800";
    default:
      return "bg-gray-100 text-gray-800";
  }
};

/**
 * Get Tailwind CSS classes for invoice status badge
 * @param status - Invoice status
 * @returns Tailwind CSS classes string
 */
export const getInvoiceStatusColor = (status: string): string => {
  switch (status) {
    case "paid":
      return "bg-green-100 text-green-800";
    case "sent":
      return "bg-blue-100 text-blue-800";
    case "overdue":
      return "bg-red-100 text-red-800";
    case "cancelled":
      return "bg-gray-100 text-gray-800";
    case "draft":
      return "bg-yellow-100 text-yellow-800";
    default:
      return "bg-gray-100 text-gray-800";
  }
};

/**
 * Get work order by ID
 * @param workOrderId - Work order ID (optional)
 * @param workOrders - Array of work orders
 * @returns Work order or null if not found
 */
export const getWorkOrderStatus = (workOrderId: string | undefined, workOrders: WorkOrder[]): WorkOrder | null => {
  if (!workOrderId) return null;
  return workOrders.find((wo) => wo.id === workOrderId) || null;
};

/**
 * Get work order badge styling and text
 * @param workOrder - Work order object (optional)
 * @returns Badge configuration object or null
 */
export const getWorkOrderBadge = (workOrder?: WorkOrder): {
  color: string;
  icon: string;
  text: string;
} | null => {
  if (!workOrder) return null;

  switch (workOrder.status) {
    case "To Do":
      return {
        color: "bg-gray-100 text-gray-800 border-gray-500",
        icon: "🔵",
        text: "Werkorder: To Do",
      };
    case "Pending":
      return {
        color: "bg-yellow-100 text-yellow-800 border-yellow-500",
        icon: "🟡",
        text: "Werkorder: In Wacht",
      };
    case "In Progress":
      return {
        color: "bg-blue-100 text-blue-800 border-blue-500",
        icon: "🟢",
        text: "Werkorder: In Uitvoering",
      };
    case "Completed":
      return {
        color: "bg-green-100 text-green-800 border-green-500",
        icon: "✅",
        text: "Werkorder: Voltooid",
      };
    default:
      return {
        color: "bg-gray-100 text-gray-800",
        icon: "❓",
        text: "Werkorder: Onbekend",
      };
  }
};

/**
 * Check if invoice is auto-generated from work order
 * @param invoice - Invoice object
 * @returns True if invoice is auto-generated
 */
export const isAutoGeneratedInvoice = (invoice: Invoice): boolean => {
  return !!(
    invoice.workOrderId ||
    (invoice.notes &&
      invoice.notes.includes("Factuur aangemaakt automatisch"))
  );
};

/**
 * Get work order for a specific invoice
 * @param invoiceId - Invoice ID
 * @param invoices - Array of invoices
 * @param workOrders - Array of work orders
 * @returns Work order or undefined if not found
 */
export const getWorkOrderForInvoice = (
  invoiceId: string,
  invoices: Invoice[],
  workOrders: WorkOrder[]
): WorkOrder | undefined => {
  const invoice = invoices.find((inv) => inv.id === invoiceId);
  if (!invoice?.workOrderId) return undefined;
  return workOrders.find((wo) => wo.id === invoice.workOrderId);
};

/**
 * Create a history entry for quote or invoice
 * @param type - "quote" or "invoice"
 * @param action - Action description
 * @param details - Details of the action
 * @param currentUser - Current user object
 * @param extra - Additional properties to include
 * @returns History entry object
 */
export const createHistoryEntry = (
  type: "quote" | "invoice",
  action: string,
  details: string,
  currentUser: User,
  extra?: any
): QuoteHistoryEntry | InvoiceHistoryEntry => {
  return {
    timestamp: new Date().toISOString(),
    action: action as any,
    performedBy: currentUser.employeeId,
    details,
    ...extra,
  };
};

