import type { Employee, Customer, InventoryItem, WorkOrder, Invoice, QuoteHistoryEntry, InvoiceHistoryEntry, User } from '../../types';

export const getEmployeeName = (id: string, employees: Employee[]): string => {
  return employees.find((e) => e.id === id)?.name || "Onbekend";
};

export const getCustomerName = (customerId: string, customers: Customer[]): string => {
  return customers.find((c) => c.id === customerId)?.name || "Onbekend";
};

export const getInventoryItemName = (itemId: string, inventory: InventoryItem[]): string => {
  return inventory.find((i) => i.id === itemId)?.name || "Onbekend item";
};

export const getQuoteStatusColor = (status: string): string => {
  switch (status) {
    case "approved":
      return "bg-green-100 text-green-800";
    case "sent":
      return "bg-blue-100 text-blue-800";
    case "rejected":
      return "bg-red-100 text-red-800";
    case "expired":
      return "bg-gray-100 text-gray-800";
    case "draft":
      return "bg-yellow-100 text-yellow-800";
    default:
      return "bg-gray-100 text-gray-800";
  }
};

export const getInvoiceStatusColor = (status: string): string => {
  switch (status) {
    case "paid":
      return "bg-green-100 text-green-800";
    case "sent":
      return "bg-blue-100 text-blue-800";
    case "overdue":
      return "bg-red-100 text-red-800";
    case "cancelled":
      return "bg-gray-100 text-gray-800";
    case "draft":
      return "bg-yellow-100 text-yellow-800";
    default:
      return "bg-gray-100 text-gray-800";
  }
};

export const getWorkOrderStatus = (workOrderId: string | undefined, workOrders: WorkOrder[]): WorkOrder | null => {
  if (!workOrderId) return null;
  return workOrders.find((wo) => wo.id === workOrderId) || null;
};

export const getWorkOrderBadge = (workOrder?: WorkOrder): {
  color: string;
  icon: string;
  text: string;
} | null => {
  if (!workOrder) return null;

  switch (workOrder.status) {
    case "To Do":
      return {
        color: "bg-gray-100 text-gray-800 border-gray-500",
        icon: "🔵",
        text: "Werkorder: To Do",
      };
    case "Pending":
      return {
        color: "bg-yellow-100 text-yellow-800 border-yellow-500",
        icon: "🟡",
        text: "Werkorder: In Wacht",
      };
    case "In Progress":
      return {
        color: "bg-blue-100 text-blue-800 border-blue-500",
        icon: "🟢",
        text: "Werkorder: In Uitvoering",
      };
    case "Completed":
      return {
        color: "bg-green-100 text-green-800 border-green-500",
        icon: "✅",
        text: "Werkorder: Voltooid",
      };
    default:
      return {
        color: "bg-gray-100 text-gray-800",
        icon: "❓",
        text: "Werkorder: Onbekend",
      };
  }
};

export const isAutoGeneratedInvoice = (invoice: Invoice): boolean => {
  return !!(
    invoice.workOrderId ||
    (invoice.notes &&
      invoice.notes.includes("Factuur aangemaakt automatisch"))
  );
};

export const getWorkOrderForInvoice = (
  invoiceId: string,
  invoices: Invoice[],
  workOrders: WorkOrder[]
): WorkOrder | undefined => {
  const invoice = invoices.find((inv) => inv.id === invoiceId);
  if (!invoice?.workOrderId) return undefined;
  return workOrders.find((wo) => wo.id === invoice.workOrderId);
};

export const createHistoryEntry = (
  type: "quote" | "invoice",
  action: string,
  details: string,
  currentUser: User,
  extra?: Partial<QuoteHistoryEntry | InvoiceHistoryEntry>
): QuoteHistoryEntry | InvoiceHistoryEntry => {
  return {
    timestamp: new Date().toISOString(),
    action: action as QuoteHistoryEntry['action'] | InvoiceHistoryEntry['action'],
    performedBy: currentUser.employeeId,
    details,
    ...extra,
  };
};

