import React, { useState } from "react";
import {
  Transaction,
  Quote,
  QuoteItem,
  QuoteLabor,
  QuoteHistoryEntry,
  Invoice,
  InvoiceHistoryEntry,
  Customer,
  InventoryItem,
  InventoryCategory,
  WorkOrder,
  Employee,
  User,
  ModuleKey,
  Notification,
} from "../types";
import { trackAction } from "../utils/analytics";
import {
  createQuoteApprovedNotification,
  createInvoiceSentNotification,
} from "../utils/smartNotifications";
import { QuoteEmailIntegration } from "../components/QuoteEmailIntegration";
import {
  validateQuoteToWorkOrder,
  validateQuoteToInvoice,
  validateInvoiceToWorkOrder,
  validateQuoteEdit,
  validateInvoiceEdit,
  getWorkflowGuardrailMessage,
  WorkflowValidationResult,
} from "../utils/workflowValidation";
import {
  getEmployeeName,
  getCustomerName,
  getInventoryItemName,
  getQuoteStatusColor,
  getInvoiceStatusColor,
  getWorkOrderStatus,
  getWorkOrderBadge,
  isAutoGeneratedInvoice,
  getWorkOrderForInvoice,
  createHistoryEntry,
} from "../features/accounting/utils/helpers";
import {
  calculateQuoteTotals as calcQuoteTotals,
  calculateInvoiceTotals as calcInvoiceTotals,
} from "../features/accounting/utils/calculations";
import {
  validateQuoteForm,
  validateInvoiceForm,
  validateQuoteItems,
  validateInvoiceItems,
  validateVatRate,
} from "../features/accounting/utils/validators";
import {
  formatCurrency,
  formatPercentage,
  formatDate,
  formatNumber,
  formatCurrencyForChart,
} from "../features/accounting/utils/formatters";
import {
  filterInvoices,
  filterQuotes,
  filterTransactions,
  calculateFilteredInvoiceTotal,
  calculateFilteredQuoteTotal,
  type InvoiceFilterOptions,
  type QuoteFilterOptions,
} from "../features/accounting/utils/filters";
import {
  createQuote,
  updateQuote,
  updateQuoteStatus as updateQuoteStatusService,
  deleteQuote as deleteQuoteService,
  cloneQuote,
  convertQuoteToInvoice as convertQuoteToInvoiceService,
  syncQuoteToWorkOrder as syncQuoteToWorkOrderService,
} from "../features/accounting/services/quoteService";
import {
  createInvoice,
  updateInvoice,
  updateInvoiceStatus as updateInvoiceStatusService,
  deleteInvoice as deleteInvoiceService,
  cloneInvoice,
  convertInvoiceToWorkOrder as convertInvoiceToWorkOrderService,
  syncInvoiceToWorkOrder as syncInvoiceToWorkOrderService,
  sendInvoiceReminder,
  shouldShowValidationModal,
} from "../features/accounting/services/invoiceService";
import { useTransactions } from "../features/accounting/hooks/useTransactions";
import { useInventorySelection } from "../features/accounting/hooks/useInventorySelection";
import { useQuoteForm } from "../features/accounting/hooks/useQuoteForm";
import { useQuotes } from "../features/accounting/hooks/useQuotes";
import { useInvoices } from "../features/accounting/hooks/useInvoices";
import { useAccountingDashboard } from "../features/accounting/hooks/useAccountingDashboard";
import { AccountingDashboard } from "../components/accounting/dashboard";
import {
  QuoteList,
  QuoteForm,
  QuoteModals,
} from "../components/accounting/quotes";
import {
  InvoiceList,
  InvoiceForm,
  InvoiceModals,
} from "../components/accounting/invoices";
import { TransactionList } from "../components/accounting/transactions";

interface AccountingProps {
  transactions: Transaction[];
  quotes: Quote[];
  setQuotes: React.Dispatch<React.SetStateAction<Quote[]>>;
  invoices: Invoice[];
  setInvoices: React.Dispatch<React.SetStateAction<Invoice[]>>;
  customers: Customer[];
  inventory: InventoryItem[];
  workOrders: WorkOrder[];
  setWorkOrders: React.Dispatch<React.SetStateAction<WorkOrder[]>>;
  employees: Employee[];
  currentUser: User;
  isAdmin: boolean;
  notifications?: Notification[];
  setNotifications?: React.Dispatch<React.SetStateAction<Notification[]>>;
  categories?: InventoryCategory[]; // 🆕 V5.7: Categories prop
}

export const Accounting: React.FC<AccountingProps> = ({
  transactions,
  quotes,
  setQuotes,
  invoices,
  setInvoices,
  customers,
  inventory,
  workOrders,
  setWorkOrders,
  employees,
  currentUser,
  isAdmin,
  notifications = [],
  setNotifications,
  categories = [],
}) => {
  const [activeTab, setActiveTab] = useState<
    "dashboard" | "transactions" | "quotes" | "invoices"
  >("dashboard");

  // 🆕 V5.7: Inventory search & filter states for quote/invoice item selection
  const {
    inventorySearchTerm,
    setInventorySearchTerm,
    inventoryCategoryFilter,
    setInventoryCategoryFilter,
    inventoryCategorySearchTerm,
    setInventoryCategorySearchTerm,
    showInventoryCategoryDropdown,
    setShowInventoryCategoryDropdown,
    filteredInventoryCategories,
    filteredInventoryForSelection,
  } = useInventorySelection(inventory, categories);

  // Dashboard navigation state - track where user came from
  const [dashboardView, setDashboardView] = useState<string | null>(null);
  const { filter, setFilter, filteredTransactions } =
    useTransactions(transactions);
  // Invoice state and handlers are now in useInvoices hook

  // Quotes hook (includes quote form)
  const quotesHook = useQuotes(
    quotes,
    setQuotes,
    inventory,
    customers,
    employees,
    currentUser,
    workOrders,
    setWorkOrders
  );

  // Extract quote form from quotes hook for backward compatibility
  const quoteForm = quotesHook.quoteForm;

  // Quote state and handlers are now in useQuotes hook
  const {
    showQuoteForm,
    setShowQuoteForm,
    showCloneQuoteModal,
    setShowCloneQuoteModal,
    showAcceptQuoteModal,
    setShowAcceptQuoteModal,
    quoteToAccept,
    setQuoteToAccept,
    cloneOnAccept,
    setCloneOnAccept,
    createQuote: handleCreateQuote,
    editQuote: handleEditQuote,
    updateQuoteStatus,
    deleteQuote,
    cloneQuote: handleCloneQuote,
    saveClonedQuote: handleSaveClonedQuote,
    acceptQuote: handleAcceptQuote,
  } = quotesHook;

  // Invoices hook (includes invoice form)
  const invoicesHook = useInvoices(
    invoices,
    setInvoices,
    inventory,
    customers,
    employees,
    currentUser,
    workOrders,
    setWorkOrders,
    setNotifications
  );

  // Extract invoice form from invoices hook for backward compatibility
  const invoiceForm = invoicesHook.invoiceForm;

  // Invoice state and handlers are now in useInvoices hook
  const {
    showInvoiceForm,
    setShowInvoiceForm,
    showCloneInvoiceModal,
    setShowCloneInvoiceModal,
    showInvoiceValidationModal,
    setShowInvoiceValidationModal,
    invoiceToValidate,
    setInvoiceToValidate,
    validationChecklist,
    setValidationChecklist,
    createInvoice: handleCreateInvoice,
    // editInvoice is defined locally with additional tab switching logic
    // updateInvoiceStatus is defined locally with additional validation modal logic
    deleteInvoice,
    // cloneInvoice is defined locally with automatic date setting
    // saveClonedInvoice is defined locally with user selection modal logic
    // sendReminder is defined locally with additional reminder date information
    // confirmInvoiceValidation is defined locally with additional checklist validation
    generateInvoiceNumber,
  } = invoicesHook;

  // 🆕 Edit states
  // editingInvoiceId is now in useInvoiceForm hook
  // 🆕 Overview Modal States
  const [showOverviewModal, setShowOverviewModal] = useState(false);
  const [overviewType, setOverviewType] = useState<
    "all" | "paid" | "outstanding" | "overdue"
  >("all");
  const [showQuotesOverviewModal, setShowQuotesOverviewModal] = useState(false);
  const [quotesOverviewType, setQuotesOverviewType] = useState<
    "all" | "approved" | "sent" | "expired"
  >("all");
  const [overviewFilter, setOverviewFilter] = useState({
    customerName: "",
    dateFrom: "",
    dateTo: "",
    minAmount: "",
    maxAmount: "",
  });

  // 🆕 Batch Operations States
  const [selectedQuotes, setSelectedQuotes] = useState<string[]>([]);
  const [selectedInvoices, setSelectedInvoices] = useState<string[]>([]);
  const [batchMode, setBatchMode] = useState(false);

  // NEW: User selection modal state
  const [showUserSelectionModal, setShowUserSelectionModal] = useState(false);
  const [conversionData, setConversionData] = useState<{
    type: "quote" | "invoice";
    sourceId: string;
    data: any;
  } | null>(null);
  const [selectedUserId, setSelectedUserId] = useState("");

  // Invoice validation modal state is now in useInvoices hook

  // Dashboard calculations are now in useAccountingDashboard hook
  const dashboard = useAccountingDashboard(
    invoices,
    quotes,
    transactions,
    customers
  );

  // Extract stats for backward compatibility
  const { totalIncome, totalExpense, netProfit } = dashboard.stats.transaction;
  const {
    totalInvoiced,
    totalPaid,
    totalOverdue,
    totalOutstanding,
    paidInvoices,
    overdueInvoices,
    outstandingInvoices,
  } = dashboard.stats.invoice;
  const {
    totalQuoted,
    totalApproved,
    totalSent,
    totalExpired,
    approvedQuotes,
    sentQuotes,
    expiredQuotes,
  } = dashboard.stats.quote;

  // Dashboard calculations are now in useAccountingDashboard hook
  // Dashboard component is now in components/accounting/dashboard/AccountingDashboard.tsx

  // Helper functions are now imported from features/accounting/utils/helpers

  // Calculation functions are now imported from features/accounting/utils/calculations
  // Quote totals are now calculated in useQuoteForm hook
  const calculateQuoteTotals = () => {
    return quoteForm.totals();
  };
  // Invoice totals are now calculated in useInvoiceForm hook
  const calculateInvoiceTotals = () => {
    return invoiceForm.totals();
  };

  // Quote CRUD Operations
  // Quote form handlers are now in useQuoteForm hook (via useQuotes)
  const {
    handleAddInventoryItem,
    handleAddCustomItem,
    handleAddLabor,
    handleRemoveItem,
    handleRemoveLabor,
    handleInventoryItemChange,
    handleItemChange,
    handleLaborChange,
  } = quoteForm;

  // Quote handlers are now in useQuotes hook
  // handleCreateQuote, handleEditQuote, handleAcceptQuote, handleCloneQuote, handleSaveClonedQuote, updateQuoteStatus, deleteQuote are already extracted above

  // Wrapper to switch to quotes tab when editing
  const handleEditQuoteWithTab = (quoteId: string) => {
    handleEditQuote(quoteId);
    setActiveTab("quotes");
  };

  // Wrapper for updateQuoteStatus to handle notifications and workorder sync
  const updateQuoteStatusWithNotifications = (
    quoteId: string,
    newStatus: Quote["status"]
  ) => {
    updateQuoteStatus(quoteId, newStatus);

    const quote = quotes.find((q) => q.id === quoteId);
    if (!quote) return;

    const updatedQuote = quotes.find((q) => q.id === quoteId);
    if (!updatedQuote) return;

    // Auto-sync to workorder if status changes
    if (updatedQuote.workOrderId && newStatus === "approved") {
      const workOrder = workOrders.find(
        (wo) => wo.id === updatedQuote.workOrderId
      );
      if (workOrder) {
        const synced = syncQuoteToWorkOrderService(updatedQuote, workOrder);
        if (synced) {
          setWorkOrders(
            workOrders.map((wo) => (wo.id === workOrder.id ? synced : wo))
          );
        }
      }
    }

    // Create smart notification when quote is approved
    if (newStatus === "approved" && setNotifications) {
      if (updatedQuote && !updatedQuote.workOrderId) {
        const notification = createQuoteApprovedNotification(
          updatedQuote,
          () => {
            // Action: Convert to work order
            convertQuoteToWorkOrder(quoteId);
          },
          () => {
            // Action: View quote (scroll to quote or show details)
            setActiveTab("quotes");
            // Could add scroll to quote functionality here
          }
        );
        setNotifications((prev) => [notification, ...prev]);
      }
    }
  };

  const handleQuoteUpdate = (quote: Quote) => {
    // Workflow validation before update
    const existingQuote = quotes.find((q) => q.id === quote.id);
    if (existingQuote) {
      const validation = validateQuoteEdit(existingQuote, workOrders);
      if (!validation.canProceed && validation.severity === "error") {
        const guardrail = getWorkflowGuardrailMessage(validation);
        alert(
          `${guardrail.icon} ${validation.message}\n\n${
            validation.suggestedAction || ""
          }`
        );
        return;
      }

      if (validation.severity === "warning") {
        const guardrail = getWorkflowGuardrailMessage(validation);
        const proceed = window.confirm(
          `${guardrail.icon} ${validation.message}\n\n${
            validation.suggestedAction || ""
          }\n\nWil je doorgaan?`
        );
        if (!proceed) return;
      }
    }

    setQuotes(quotes.map((q) => (q.id === quote.id ? quote : q)));

    // Sync to workorder if exists
    if (quote.workOrderId) {
      const synced = syncQuoteToWorkOrder(quote.id);
      if (synced) {
        alert("✅ Offerte en werkorder succesvol gesynchroniseerd!");
      }
    }
  };

  // deleteQuote is now in useQuotes hook

  // Convert Quote to Invoice
  const convertQuoteToInvoice = (quoteId: string) => {
    const quote = quotes.find((q) => q.id === quoteId);
    if (!quote) return;

    try {
      const { invoice, updatedQuote } = convertQuoteToInvoiceService(
        quote,
        currentUser,
        employees,
        invoices
      );

      setInvoices([...invoices, invoice]);
      setQuotes(quotes.map((q) => (q.id === quoteId ? updatedQuote : q)));

      alert(`✅ Factuur ${invoice.invoiceNumber} succesvol aangemaakt!`);
      setActiveTab("invoices");
    } catch (error) {
      alert((error as Error).message || "Er is een fout opgetreden!");
    }
  };

  // NEW: Convert Quote to Work Order
  const convertQuoteToWorkOrder = (quoteId: string) => {
    const quote = quotes.find((q) => q.id === quoteId);
    if (!quote) return;

    // Workflow validation
    const validation = validateQuoteToWorkOrder(quote, workOrders);
    if (!validation.canProceed) {
      const guardrail = getWorkflowGuardrailMessage(validation);
      alert(
        `${guardrail.icon} ${validation.message}\n\n${
          validation.suggestedAction || ""
        }`
      );
      return;
    }

    // Check materiaal voorraad
    for (const item of quote.items) {
      if (item.inventoryItemId) {
        const inventoryItem = inventory.find(
          (i) => i.id === item.inventoryItemId
        );
        if (inventoryItem && inventoryItem.quantity < item.quantity) {
          const confirmCreate = confirm(
            `Waarschuwing: Niet genoeg voorraad van ${inventoryItem.name}. Beschikbaar: ${inventoryItem.quantity}, Nodig: ${item.quantity}. Toch werkorder aanmaken?`
          );
          if (!confirmCreate) return;
        }
      }
    }

    const customerName =
      customers.find((c) => c.id === quote.customerId)?.name || "Onbekend";
    const totalHours =
      quote.labor?.reduce((sum, labor) => sum + labor.hours, 0) || 0;

    // Track conversion action
    trackAction(
      currentUser.employeeId,
      currentUser.role,
      ModuleKey.ACCOUNTING,
      "convert_to_workorder",
      "create",
      {
        quoteId: quote.id,
        customerId: quote.customerId,
        totalValue: quote.total,
      }
    );

    // OPEN USER SELECTION MODAL
    setConversionData({
      type: "quote",
      sourceId: quoteId,
      data: { customerName, totalHours, quote },
    });
    setSelectedUserId("");
    setShowUserSelectionModal(true);
  };

  // NEW: Convert Invoice to Work Order
  const convertInvoiceToWorkOrder = (invoiceId: string) => {
    const invoice = invoices.find((inv) => inv.id === invoiceId);
    if (!invoice) return;

    if (invoice.status !== "sent" && invoice.status !== "draft") {
      alert(
        "Alleen verzonden of concept facturen kunnen worden omgezet naar werkorders!"
      );
      return;
    }

    if (invoice.workOrderId) {
      alert("Deze factuur heeft al een gekoppelde werkorder!");
      return;
    }

    // Check materiaal voorraad
    for (const item of invoice.items) {
      if (item.inventoryItemId) {
        const inventoryItem = inventory.find(
          (i) => i.id === item.inventoryItemId
        );
        if (inventoryItem && inventoryItem.quantity < item.quantity) {
          const confirmCreate = confirm(
            `Waarschuwing: Niet genoeg voorraad van ${inventoryItem.name}. Beschikbaar: ${inventoryItem.quantity}, Nodig: ${item.quantity}. Toch werkorder aanmaken?`
          );
          if (!confirmCreate) return;
        }
      }
    }

    const customerName =
      customers.find((c) => c.id === invoice.customerId)?.name || "Onbekend";
    const totalHours =
      invoice.labor?.reduce((sum, labor) => sum + labor.hours, 0) || 0;

    // OPEN USER SELECTION MODAL
    setConversionData({
      type: "invoice",
      sourceId: invoiceId,
      data: { customerName, totalHours, invoice },
    });
    setSelectedUserId("");
    setShowUserSelectionModal(true);
  };

  // Get WorkOrder status for Quote/Invoice
  // Helper functions are now imported from features/accounting/utils/helpers

  // 🆕 Overview Functions
  const openOverviewModal = (
    type: "all" | "paid" | "outstanding" | "overdue"
  ) => {
    setOverviewType(type);
    setShowOverviewModal(true);
  };

  const resetFilters = () => {
    setOverviewFilter({
      customerName: "",
      dateFrom: "",
      dateTo: "",
      minAmount: "",
      maxAmount: "",
    });
  };

  // Filter functions are now imported from features/accounting/utils/filters
  const getFilteredInvoices = () => {
    const filterOptions: InvoiceFilterOptions = {
      type: overviewType,
      customerName: overviewFilter.customerName,
      dateFrom: overviewFilter.dateFrom,
      dateTo: overviewFilter.dateTo,
      minAmount: overviewFilter.minAmount,
      maxAmount: overviewFilter.maxAmount,
    };
    return filterInvoices(invoices, customers, filterOptions);
  };

  const getFilteredTotal = () => {
    return calculateFilteredInvoiceTotal(getFilteredInvoices());
  };

  // 🆕 Quotes Overview Functions
  const openQuotesOverviewModal = (
    type: "all" | "approved" | "sent" | "expired"
  ) => {
    setQuotesOverviewType(type);
    setShowQuotesOverviewModal(true);
  };

  // Filter functions are now imported from features/accounting/utils/filters
  const getFilteredQuotes = () => {
    const filterOptions: QuoteFilterOptions = {
      type: quotesOverviewType,
      customerName: overviewFilter.customerName,
      dateFrom: overviewFilter.dateFrom,
      dateTo: overviewFilter.dateTo,
      minAmount: overviewFilter.minAmount,
      maxAmount: overviewFilter.maxAmount,
    };
    return filterQuotes(quotes, customers, filterOptions);
  };

  const getFilteredQuotesTotal = () => {
    return calculateFilteredQuoteTotal(getFilteredQuotes());
  };

  // Complete conversion with selected user
  const completeConversion = () => {
    if (!selectedUserId) {
      alert("Selecteer een medewerker!");
      return;
    }

    if (!conversionData) return;

    if (conversionData.type === "quote") {
      executeQuoteToWorkOrderConversion(
        conversionData.sourceId,
        selectedUserId,
        conversionData.data
      );
    } else {
      executeInvoiceToWorkOrderConversion(
        conversionData.sourceId,
        selectedUserId,
        conversionData.data
      );
    }

    setShowUserSelectionModal(false);
    setConversionData(null);
    setSelectedUserId("");
  };

  // Execute the actual conversion after user is selected - FOR QUOTE
  const executeQuoteToWorkOrderConversion = (
    quoteId: string,
    userId: string,
    data: any
  ) => {
    const quote = quotes.find((q) => q.id === quoteId);
    if (!quote) return;

    const now = new Date().toISOString();
    const workOrderId = `wo${Date.now()}`;

    const workOrder: WorkOrder = {
      id: workOrderId,
      title: `${data.customerName} - Offerte ${quote.id}`,
      description:
        quote.notes || `Werkorder aangemaakt vanuit offerte ${quote.id}`,
      status: "To Do",
      assignedTo: userId,
      assignedBy: currentUser.employeeId,
      convertedBy: currentUser.employeeId,
      requiredInventory: quote.items
        .filter((item) => item.inventoryItemId)
        .map((item) => ({
          itemId: item.inventoryItemId!,
          quantity: item.quantity,
        })),
      createdDate: new Date().toISOString().split("T")[0],
      customerId: quote.customerId,
      location: quote.location,
      scheduledDate: quote.scheduledDate,
      quoteId: quote.id,
      estimatedHours: data.totalHours,
      estimatedCost: quote.total,
      notes: `Geschatte uren: ${
        data.totalHours
      }u\nGeschatte kosten: ${formatCurrency(quote.total)}`,
      // NEW TIMESTAMPS
      timestamps: {
        created: now,
        converted: now,
        assigned: now,
      },
      // NEW HISTORY
      history: [
        createHistoryEntry(
          "quote",
          "created",
          `Werkorder aangemaakt door ${getEmployeeName(
            currentUser.employeeId,
            employees
          )}`,
          currentUser
        ) as any,
        createHistoryEntry(
          "quote",
          "converted",
          `Geconverteerd van offerte ${quote.id} door ${getEmployeeName(
            currentUser.employeeId,
            employees
          )}`,
          currentUser
        ) as any,
        {
          timestamp: now,
          action: "assigned" as const,
          performedBy: currentUser.employeeId,
          details: `Toegewezen aan ${getEmployeeName(
            userId,
            employees
          )} door ${getEmployeeName(currentUser.employeeId, employees)}`,
          toAssignee: userId,
        },
      ],
    };

    setWorkOrders([...workOrders, workOrder]);

    // Update quote met workOrderId
    setQuotes(
      quotes.map((q) => {
        if (q.id === quoteId) {
          return {
            ...q,
            workOrderId: workOrder.id,
            timestamps: {
              ...q.timestamps,
              convertedToWorkOrder: now,
            },
            history: [
              ...(q.history || []),
              createHistoryEntry(
                "quote",
                "converted_to_workorder",
                `Geconverteerd naar werkorder ${
                  workOrder.id
                } door ${getEmployeeName(currentUser.employeeId, employees)}`,
                currentUser
              ) as QuoteHistoryEntry,
            ],
          };
        }
        return q;
      })
    );

    alert(
      `✅ Werkorder ${
        workOrder.id
      } succesvol aangemaakt en toegewezen aan ${getEmployeeName(
        userId,
        employees
      )}!`
    );
  };

  // Execute the actual conversion after user is selected - FOR INVOICE
  const executeInvoiceToWorkOrderConversion = (
    invoiceId: string,
    userId: string,
    data: any
  ) => {
    const invoice = invoices.find((inv) => inv.id === invoiceId);
    if (!invoice) return;

    const now = new Date().toISOString();
    const workOrderId = `wo${Date.now()}`;

    const workOrder: WorkOrder = {
      id: workOrderId,
      title: `${data.customerName} - Factuur ${data.invoice.invoiceNumber}`,
      description:
        data.invoice.notes ||
        `Werkorder aangemaakt vanuit factuur ${data.invoice.invoiceNumber}`,
      status: "To Do",
      assignedTo: userId,
      assignedBy: currentUser.employeeId,
      convertedBy: currentUser.employeeId,
      requiredInventory: data.invoice.items
        .filter((item: any) => item.inventoryItemId)
        .map((item: any) => ({
          itemId: item.inventoryItemId!,
          quantity: item.quantity,
        })),
      createdDate: new Date().toISOString().split("T")[0],
      customerId: data.invoice.customerId,
      location: data.invoice.location,
      scheduledDate: data.invoice.scheduledDate,
      invoiceId: invoice.id,
      estimatedHours: data.totalHours,
      estimatedCost: data.invoice.total,
      notes: `Geschatte uren: ${
        data.totalHours
      }u\nGeschatte kosten: ${formatCurrency(data.invoice.total)}`,
      // NEW TIMESTAMPS
      timestamps: {
        created: now,
        converted: now,
        assigned: now,
      },
      // NEW HISTORY
      history: [
        createHistoryEntry(
          "invoice",
          "created",
          `Werkorder aangemaakt door ${getEmployeeName(
            currentUser.employeeId,
            employees
          )}`,
          currentUser
        ) as any,
        createHistoryEntry(
          "invoice",
          "converted",
          `Geconverteerd van factuur ${
            data.invoice.invoiceNumber
          } door ${getEmployeeName(currentUser.employeeId, employees)}`,
          currentUser
        ) as any,
        {
          timestamp: now,
          action: "assigned" as const,
          performedBy: currentUser.employeeId,
          details: `Toegewezen aan ${getEmployeeName(
            userId,
            employees
          )} door ${getEmployeeName(currentUser.employeeId, employees)}`,
          toAssignee: userId,
        },
      ],
    };

    setWorkOrders([...workOrders, workOrder]);

    // Update invoice met workOrderId
    setInvoices(
      invoices.map((inv) => {
        if (inv.id === invoiceId) {
          return {
            ...inv,
            workOrderId: workOrder.id,
            timestamps: {
              ...inv.timestamps,
              convertedToWorkOrder: now,
            },
            history: [
              ...(inv.history || []),
              createHistoryEntry(
                "invoice",
                "converted_to_workorder",
                `Geconverteerd naar werkorder ${
                  workOrder.id
                } door ${getEmployeeName(currentUser.employeeId, employees)}`,
                currentUser
              ) as InvoiceHistoryEntry,
            ],
          };
        }
        return inv;
      })
    );

    alert(
      `✅ Werkorder ${
        workOrder.id
      } succesvol aangemaakt en toegewezen aan ${getEmployeeName(
        userId,
        employees
      )}!`
    );
  };

  // Sync Quote changes to WorkOrder
  const syncQuoteToWorkOrder = (quoteId: string) => {
    const quote = quotes.find((q) => q.id === quoteId);
    if (!quote || !quote.workOrderId) return false;

    const workOrder = workOrders.find((wo) => wo.id === quote.workOrderId);
    if (!workOrder) return false;

    // Check if workorder is completed
    if (workOrder.status === "Completed") {
      alert(
        "❌ Deze werkorder is al voltooid. Wijzigingen zijn niet meer mogelijk (behalve notities)."
      );
      return false;
    }

    // Warning if in progress
    if (workOrder.status === "In Progress") {
      const confirmSync = window.confirm(
        "⚠️ Deze werkorder is momenteel actief. Weet je zeker dat je wijzigingen wilt doorvoeren? De toegewezen medewerker ontvangt een notificatie."
      );
      if (!confirmSync) return false;
    }

    // Use service function
    const updatedWorkOrder = syncQuoteToWorkOrderService(quote, workOrder);
    if (!updatedWorkOrder) return false;

    setWorkOrders(
      workOrders.map((wo) => (wo.id === workOrder.id ? updatedWorkOrder : wo))
    );

    return true;
  };

  // Sync Invoice changes to WorkOrder
  const syncInvoiceToWorkOrder = (invoiceId: string) => {
    const invoice = invoices.find((inv) => inv.id === invoiceId);
    if (!invoice || !invoice.workOrderId) return false;

    const workOrder = workOrders.find((wo) => wo.id === invoice.workOrderId);
    if (!workOrder) return false;

    // Check if workorder is completed
    if (workOrder.status === "Completed") {
      alert(
        "❌ Deze werkorder is al voltooid. Wijzigingen zijn niet meer mogelijk (behalve notities)."
      );
      return false;
    }

    // Warning if in progress
    if (workOrder.status === "In Progress") {
      const confirmSync = window.confirm(
        "⚠️ Deze werkorder is momenteel actief. Weet je zeker dat je wijzigingen wilt doorvoeren? De toegewezen medewerker ontvangt een notificatie."
      );
      if (!confirmSync) return false;
    }

    // Use service function
    const updatedWorkOrder = syncInvoiceToWorkOrderService(invoice, workOrder);
    if (!updatedWorkOrder) return false;

    setWorkOrders(
      workOrders.map((wo) => (wo.id === workOrder.id ? updatedWorkOrder : wo))
    );

    return true;
  };

  // Invoice CRUD Operations
  // Invoice form handlers are now in useInvoiceForm hook
  const {
    handleAddInventoryItem: handleAddInvoiceInventoryItem,
    handleAddCustomItem: handleAddInvoiceCustomItem,
    handleAddLabor: handleAddInvoiceLabor,
    handleRemoveItem: handleRemoveInvoiceItem,
    handleRemoveLabor: handleRemoveInvoiceLabor,
    handleInventoryItemChange: handleInvoiceInventoryItemChange,
    handleItemChange: handleInvoiceItemChange,
    handleLaborChange: handleInvoiceLaborChange,
  } = invoiceForm;

  // Check if invoice was automatically created from work order
  // Helper functions are now imported from features/accounting/utils/helpers

  const updateInvoiceStatus = (
    invoiceId: string,
    newStatus: Invoice["status"]
  ) => {
    const invoice = invoices.find((inv) => inv.id === invoiceId);
    if (!invoice) return;

    // Tip 4: Show validation modal for draft invoices being sent, especially auto-generated ones
    if (newStatus === "sent" && invoice.status === "draft") {
      if (shouldShowValidationModal(invoice)) {
        // Show validation modal for auto-generated invoices
        setInvoiceToValidate(invoice);
        setValidationChecklist({
          hoursChecked: false,
          materialsChecked: false,
          extraWorkAdded: false,
        });
        setShowInvoiceValidationModal(true);
        return; // Don't update yet, wait for validation
      }
    }

    // Use service function
    const updatedInvoice = updateInvoiceStatusService(
      invoice,
      newStatus,
      currentUser,
      employees
    );

    setInvoices(
      invoices.map((inv) => (inv.id === invoiceId ? updatedInvoice : inv))
    );

    // Track analytics
    if (newStatus === "sent") {
      trackAction(
        currentUser.employeeId,
        currentUser.role,
        ModuleKey.ACCOUNTING,
        "validate_invoice",
        "complete",
        {
          invoiceId: invoice.id,
          invoiceNumber: invoice.invoiceNumber,
          wasAutoGenerated: isAutoGeneratedInvoice(invoice),
        }
      );
    } else if (newStatus === "paid") {
      trackAction(
        currentUser.employeeId,
        currentUser.role,
        ModuleKey.ACCOUNTING,
        "mark_invoice_paid",
        "complete",
        {
          invoiceId: invoice.id,
          invoiceNumber: invoice.invoiceNumber,
          total: invoice.total,
        }
      );
    }
  };

  // Tip 4: Confirm invoice validation and send
  const confirmInvoiceValidation = () => {
    if (!invoiceToValidate) return;

    // Check if all items are checked (at least hours and materials)
    if (
      !validationChecklist.hoursChecked ||
      !validationChecklist.materialsChecked
    ) {
      alert("⚠️ Controleer minimaal de uren en materialen voordat u verzendt.");
      return;
    }

    // Directly update invoice status to "sent" without going through validation check again
    const invoice = invoices.find((inv) => inv.id === invoiceToValidate.id);
    if (!invoice) return;

    const now = new Date().toISOString();
    const oldStatus = invoice.status;

    const updates: Partial<Invoice> = {
      status: "sent",
      history: [
        ...(invoice.history || []),
        createHistoryEntry(
          "invoice",
          "sent",
          `Status gewijzigd van "${oldStatus}" naar "sent" na validatie door ${getEmployeeName(
            currentUser.employeeId,
            employees
          )}`,
          currentUser,
          { fromStatus: oldStatus, toStatus: "sent" }
        ) as InvoiceHistoryEntry,
      ],
    };

    // Update timestamps
    if (!invoice.timestamps) {
      updates.timestamps = { created: invoice.issueDate };
    } else {
      updates.timestamps = { ...invoice.timestamps };
    }

    if (!updates.timestamps.sent) {
      updates.timestamps.sent = now;

      // 🆕 V5.6: Automatische herinneringsplanning bij verzenden
      if (invoice.dueDate) {
        const dueDate = new Date(invoice.dueDate);
        const reminder1Date = new Date(dueDate);
        reminder1Date.setDate(dueDate.getDate() + 7); // +7 dagen na vervaldatum

        const reminder2Date = new Date(dueDate);
        reminder2Date.setDate(dueDate.getDate() + 14); // +14 dagen na vervaldatum

        updates.reminders = {
          reminder1Date: reminder1Date.toISOString().split("T")[0],
          reminder1Sent: false,
          reminder2Date: reminder2Date.toISOString().split("T")[0],
          reminder2Sent: false,
        };
      }

      // Track invoice validation completion
      trackAction(
        currentUser.employeeId,
        currentUser.role,
        ModuleKey.ACCOUNTING,
        "validate_invoice",
        "complete",
        {
          invoiceId: invoice.id,
          invoiceNumber: invoice.invoiceNumber,
          wasAutoGenerated: isAutoGeneratedInvoice(invoice),
        }
      );
    }

    // Update invoice in state
    setInvoices(
      invoices.map((inv) =>
        inv.id === invoice.id ? { ...inv, ...updates } : inv
      )
    );

    // Close modal and reset
    setShowInvoiceValidationModal(false);
    setInvoiceToValidate(null);
    setValidationChecklist({
      hoursChecked: false,
      materialsChecked: false,
      extraWorkAdded: false,
    });

    // Show success message
    alert(
      `✅ Factuur ${invoice.invoiceNumber} succesvol gevalideerd en verzonden!`
    );
  };

  const handleEditInvoice = (invoiceId: string) => {
    const invoice = invoices.find((inv) => inv.id === invoiceId);
    if (!invoice) return;

    // Pre-fill form with invoice data using hook
    invoiceForm.loadInvoiceForEditing({
      customerId: invoice.customerId,
      items: invoice.items,
      labor: invoice.labor || [],
      vatRate: invoice.vatRate,
      notes: invoice.notes || "",
      paymentTerms: invoice.paymentTerms || "14 dagen",
      issueDate: invoice.issueDate,
      dueDate: invoice.dueDate,
    });

    // Store editing invoice ID
    invoiceForm.setEditingInvoiceId(invoiceId);

    // Open form and switch to invoices tab
    setActiveTab("invoices");
    setShowInvoiceForm(true);
  };

  const handleInvoiceUpdate = (invoice: Invoice) => {
    setInvoices(invoices.map((inv) => (inv.id === invoice.id ? invoice : inv)));

    // Sync to workorder if exists
    if (invoice.workOrderId) {
      const workOrder = workOrders.find((wo) => wo.id === invoice.workOrderId);
      if (workOrder) {
        const synced = syncInvoiceToWorkOrderService(invoice, workOrder);
        if (synced) {
          setWorkOrders(
            workOrders.map((wo) => (wo.id === workOrder.id ? synced : wo))
          );
          alert("✅ Factuur en werkorder succesvol gesynchroniseerd!");
        }
      }
    }
  };

  // handleCloneQuote and handleSaveClonedQuote are now in useQuotes hook

  // 🆕 CLONE INVOICE FUNCTION
  const handleCloneInvoice = (invoiceId: string) => {
    const invoice = invoices.find((inv) => inv.id === invoiceId);
    if (!invoice) return;

    const today = new Date().toISOString().split("T")[0];
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 14); // +14 days

    // Prepare clone data with new invoice number and reset fields using hook
    invoiceForm.setFields({
      customerId: invoice.customerId,
      items: invoice.items,
      labor: invoice.labor || [],
      vatRate: invoice.vatRate,
      notes: invoice.notes || "",
      paymentTerms: invoice.paymentTerms,
      issueDate: today,
      dueDate: dueDate.toISOString().split("T")[0],
    });
    setShowCloneInvoiceModal(true);
  };

  const handleSaveClonedInvoice = (sendToWorkOrder: boolean = false) => {
    // Validate form
    if (!invoiceForm.validate()) {
      alert(invoiceForm.errors._form || "Vul alle verplichte velden in!");
      return;
    }

    const { subtotal, vatAmount, total } = calculateInvoiceTotals();
    const now = new Date().toISOString();
    const customerName = getCustomerName(
      invoiceForm.formData.customerId,
      customers
    );

    const invoice: Invoice = {
      id: `inv${Date.now()}`,
      invoiceNumber: generateInvoiceNumber(),
      customerId: invoiceForm.formData.customerId,
      items: invoiceForm.formData.items,
      labor:
        invoiceForm.formData.labor.length > 0
          ? invoiceForm.formData.labor
          : undefined,
      subtotal: subtotal,
      vatRate: invoiceForm.formData.vatRate,
      vatAmount: vatAmount,
      total: total,
      status: "draft",
      issueDate: invoiceForm.formData.issueDate,
      dueDate: invoiceForm.formData.dueDate,
      notes: invoiceForm.formData.notes,
      paymentTerms: invoiceForm.formData.paymentTerms,
      createdBy: currentUser.employeeId,
      timestamps: {
        created: now,
      },
      history: [
        createHistoryEntry(
          "invoice",
          "created",
          `Factuur gecloneerd door ${getEmployeeName(
            currentUser.employeeId,
            employees
          )} voor klant ${customerName}`,
          currentUser
        ) as InvoiceHistoryEntry,
      ],
    };

    setInvoices([...invoices, invoice]);

    // Reset form
    invoiceForm.reset();

    setShowCloneInvoiceModal(false);

    // If sendToWorkOrder is true, open user selection modal
    if (sendToWorkOrder) {
      const totalHours =
        invoice.labor?.reduce((sum, labor) => sum + labor.hours, 0) || 0;

      setConversionData({
        type: "invoice",
        sourceId: invoice.id,
        data: { customerName, totalHours, invoice },
      });
      setSelectedUserId("");
      setShowUserSelectionModal(true);
    } else {
      alert(`✅ Factuur ${invoice.invoiceNumber} succesvol gecloneerd!`);

      // Scroll to the new invoice
      setTimeout(() => {
        const element = document.getElementById(invoice.id);
        element?.scrollIntoView({ behavior: "smooth", block: "center" });
      }, 100);
    }
  };

  const handleSaveClonedInvoiceAndSendToWorkOrder = () => {
    handleSaveClonedInvoice(true);
  };

  // 🆕 V5.6: Send reminder manually
  const handleSendReminder = (invoiceId: string, reminderNumber: 1 | 2) => {
    const invoice = invoices.find((inv) => inv.id === invoiceId);
    if (!invoice || !invoice.reminders) return;

    try {
      const updatedInvoice = sendInvoiceReminder(
        invoice,
        reminderNumber,
        currentUser,
        employees
      );

      setInvoices(
        invoices.map((inv) => (inv.id === invoiceId ? updatedInvoice : inv))
      );

      const reminderDate =
        reminderNumber === 1
          ? invoice.reminders.reminder1Date
          : invoice.reminders.reminder2Date;
      alert(
        `✅ Herinnering ${reminderNumber} verzonden voor factuur ${
          invoice.invoiceNumber
        }\n\n📧 Template: "Betreft factuur ${
          invoice.invoiceNumber
        } – vriendelijke herinnering"${
          reminderDate
            ? `\n📅 Gepland voor: ${new Date(reminderDate).toLocaleDateString(
                "nl-NL"
              )}`
            : ""
        }`
      );
    } catch (error) {
      alert((error as Error).message || "Er is een fout opgetreden!");
    }
  };

  return (
    <div className="p-4 sm:p-6 lg:p-8">
      <h1 className="text-2xl sm:text-3xl font-bold text-neutral mb-2">
        Facturen en Offerte
      </h1>
      <p className="text-sm sm:text-base text-gray-600 mb-4 sm:mb-8">
        Genereer offertes, facturen en beheer financiële gegevens
      </p>

      {/* Invoice Modals */}
      <InvoiceModals
        showOverviewModal={showOverviewModal}
        setShowOverviewModal={setShowOverviewModal}
        overviewType={overviewType}
        setOverviewType={setOverviewType}
        overviewFilter={overviewFilter}
        setOverviewFilter={setOverviewFilter}
        resetFilters={resetFilters}
        invoices={invoices}
        customers={customers}
        workOrders={workOrders}
        onEdit={handleEditInvoice}
        onClone={handleCloneInvoice}
        onConvertToWorkOrder={convertInvoiceToWorkOrder}
        showCloneInvoiceModal={showCloneInvoiceModal}
        setShowCloneInvoiceModal={setShowCloneInvoiceModal}
        invoiceForm={invoiceForm}
        calculateInvoiceTotals={calculateInvoiceTotals}
        onSaveClonedInvoice={handleSaveClonedInvoice}
        onSaveClonedInvoiceAndSendToWorkOrder={
          handleSaveClonedInvoiceAndSendToWorkOrder
        }
        showInvoiceValidationModal={showInvoiceValidationModal}
        setShowInvoiceValidationModal={setShowInvoiceValidationModal}
        invoiceToValidate={invoiceToValidate}
        setInvoiceToValidate={setInvoiceToValidate}
        validationChecklist={validationChecklist}
        setValidationChecklist={setValidationChecklist}
        onConfirmValidation={confirmInvoiceValidation}
      />

      {/* 🆕 Overview Modal with Filters - REMOVED - Now in InvoiceModals */}
      {/* Old overview modal code removed - now in InvoiceModals component */}

      {/* User Selection Modal */}
      {showUserSelectionModal && conversionData && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-xl max-w-lg w-full p-6">
            <h2 className="text-2xl font-semibold text-neutral mb-4">
              👤 Medewerker Toewijzen
            </h2>

            <div className="mb-6">
              <p className="text-gray-700 mb-4">
                Je gaat een werkorder aanmaken van deze{" "}
                {conversionData.type === "quote" ? "offerte" : "factuur"}. Aan
                welke medewerker wil je deze werkorder toewijzen?
              </p>

              <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg mb-4">
                <div className="flex items-center gap-2 mb-2">
                  <svg
                    className="w-5 h-5 text-blue-600"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  <span className="text-sm font-semibold text-blue-800">
                    Werkorder Details
                  </span>
                </div>
                <div className="text-sm text-gray-700 space-y-1">
                  <p>
                    <strong>Klant:</strong> {conversionData.data.customerName}
                  </p>
                  <p>
                    <strong>Geschatte uren:</strong>{" "}
                    {conversionData.data.totalHours}u
                  </p>
                  <p>
                    <strong>Waarde:</strong> €
                    {conversionData.type === "quote"
                      ? formatCurrency(conversionData.data.quote.total)
                      : formatCurrency(conversionData.data.invoice.total)}
                  </p>
                </div>
              </div>

              <label className="block text-sm font-medium text-gray-700 mb-2">
                Selecteer Medewerker *
              </label>
              <select
                value={selectedUserId}
                onChange={(e) => setSelectedUserId(e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
              >
                <option value="">-- Kies een medewerker --</option>
                {employees.map((emp) => (
                  <option key={emp.id} value={emp.id}>
                    {emp.name} - {emp.role}
                  </option>
                ))}
              </select>
            </div>

            <div className="flex gap-3">
              <button
                onClick={completeConversion}
                disabled={!selectedUserId}
                className={`flex-1 px-6 py-3 rounded-lg font-semibold transition-colors ${
                  selectedUserId
                    ? "bg-primary text-white hover:bg-secondary"
                    : "bg-gray-300 text-gray-500 cursor-not-allowed"
                }`}
              >
                ✓ Werkorder Aanmaken
              </button>
              <button
                onClick={() => {
                  setShowUserSelectionModal(false);
                  setConversionData(null);
                  setSelectedUserId("");
                }}
                className="px-6 py-3 bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 transition-colors font-semibold"
              >
                Annuleren
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Quote Modals */}
      <QuoteModals
        showQuotesOverviewModal={showQuotesOverviewModal}
        setShowQuotesOverviewModal={setShowQuotesOverviewModal}
        quotesOverviewType={quotesOverviewType}
        setQuotesOverviewType={setQuotesOverviewType}
        overviewFilter={overviewFilter}
        setOverviewFilter={setOverviewFilter}
        resetFilters={resetFilters}
        quotes={quotes}
        customers={customers}
        workOrders={workOrders}
        onEdit={handleEditQuoteWithTab}
        onClone={handleCloneQuote}
        onConvertToWorkOrder={convertQuoteToWorkOrder}
        showAcceptQuoteModal={showAcceptQuoteModal}
        setShowAcceptQuoteModal={setShowAcceptQuoteModal}
        quoteToAccept={quoteToAccept}
        setQuoteToAccept={setQuoteToAccept}
        cloneOnAccept={cloneOnAccept}
        setCloneOnAccept={setCloneOnAccept}
        onAccept={handleAcceptQuote}
        showCloneQuoteModal={showCloneQuoteModal}
        setShowCloneQuoteModal={setShowCloneQuoteModal}
        quoteForm={quoteForm}
        calculateQuoteTotals={calculateQuoteTotals}
        onSaveClonedQuote={handleSaveClonedQuote}
      />

      {/* Clone Invoice Modal - REMOVED - Now in InvoiceModals */}
      {/* Old clone invoice modal code removed - now in InvoiceModals component */}

      {/* Tabs */}
      <div className="flex gap-2 sm:gap-3 mb-6 sm:mb-8 flex-wrap">
        <button
          onClick={() => {
            setActiveTab("dashboard");
            setDashboardView(null);
          }}
          className={`px-4 sm:px-6 py-2 rounded-lg font-medium transition-colors text-sm sm:text-base ${
            activeTab === "dashboard"
              ? "bg-primary text-white"
              : "bg-gray-200 text-gray-700 hover:bg-gray-300"
          }`}
        >
          📊 Dashboard
        </button>
        <button
          onClick={() => setActiveTab("transactions")}
          className={`px-4 sm:px-6 py-2 rounded-lg font-medium transition-colors text-sm sm:text-base ${
            activeTab === "transactions"
              ? "bg-primary text-white"
              : "bg-gray-200 text-gray-700 hover:bg-gray-300"
          }`}
        >
          💰 Transacties
        </button>
        <button
          onClick={() => setActiveTab("quotes")}
          className={`px-4 sm:px-6 py-2 rounded-lg font-medium transition-colors text-sm sm:text-base ${
            activeTab === "quotes"
              ? "bg-primary text-white"
              : "bg-gray-200 text-gray-700 hover:bg-gray-300"
          }`}
        >
          📋 Offertes
        </button>
        <button
          onClick={() => setActiveTab("invoices")}
          className={`px-4 sm:px-6 py-2 rounded-lg font-medium transition-colors text-sm sm:text-base ${
            activeTab === "invoices"
              ? "bg-primary text-white"
              : "bg-gray-200 text-gray-700 hover:bg-gray-300"
          }`}
        >
          🧾 Facturen
        </button>
      </div>

      {/* Back to Dashboard button (when not on dashboard) */}
      {activeTab !== "dashboard" && (
        <button
          onClick={() => {
            setActiveTab("dashboard");
            setDashboardView(null);
          }}
          className="flex items-center gap-2 text-primary hover:text-secondary transition-colors mb-4"
        >
          <svg
            className="w-5 h-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M10 19l-7-7m0 0l7-7m-7 7h18"
            />
          </svg>
          Terug naar Dashboard
        </button>
      )}

      {/* Dashboard Tab */}
      {activeTab === "dashboard" && (
        <AccountingDashboard
          invoices={invoices}
          quotes={quotes}
          transactions={transactions}
          customers={customers}
          onNavigate={(view, data) => {
            setDashboardView(view);
            if (view === "invoices") {
              setActiveTab("invoices");
              if (data?.overviewType) {
                setOverviewType(data.overviewType);
                setShowOverviewModal(true);
              }
            } else if (view === "quotes") {
              setActiveTab("quotes");
              if (data?.overviewType) {
                setQuotesOverviewType(data.overviewType);
                setShowQuotesOverviewModal(true);
              }
            } else {
              setActiveTab(view as "transactions" | "quotes" | "invoices");
            }
          }}
        />
      )}

      {/* Transactions Tab */}
      {activeTab === "transactions" && (
        <TransactionList
          transactions={transactions}
          filteredTransactions={filteredTransactions}
          filter={filter}
          setFilter={setFilter}
          totalIncome={totalIncome}
          totalExpense={totalExpense}
          netProfit={netProfit}
        />
      )}

      {/* Quotes Tab - Existing content continues here... */}
      {activeTab === "quotes" && (
        <>
          {/* 📧 Email Parsing Integration */}
          {isAdmin && (
            <div className="mb-6">
              <QuoteEmailIntegration
                customers={customers}
                onQuoteCreated={(quote) => {
                  setQuotes([...quotes, quote]);
                  alert(
                    `✅ Offerte ${quote.id} succesvol aangemaakt vanuit email!`
                  );
                }}
              />
            </div>
          )}

          <QuoteList
            quotes={quotes}
            customers={customers}
            workOrders={workOrders}
            invoices={invoices}
            inventory={inventory}
            isAdmin={isAdmin}
            totalQuoted={totalQuoted}
            totalApproved={totalApproved}
            totalSent={totalSent}
            totalExpired={totalExpired}
            approvedQuotes={approvedQuotes}
            sentQuotes={sentQuotes}
            expiredQuotes={expiredQuotes}
            batchMode={batchMode}
            setBatchMode={setBatchMode}
            selectedQuotes={selectedQuotes}
            setSelectedQuotes={setSelectedQuotes}
            setShowQuoteForm={setShowQuoteForm}
            onOpenOverviewModal={openQuotesOverviewModal}
            onConvertToWorkOrder={convertQuoteToWorkOrder}
            onConvertToInvoice={convertQuoteToInvoice}
            onUpdateStatus={updateQuoteStatusWithNotifications}
            onClone={handleCloneQuote}
            onDelete={deleteQuote}
            onAccept={(quoteId) => {
              setQuoteToAccept(quoteId);
              setCloneOnAccept(false);
              setShowAcceptQuoteModal(true);
            }}
            onEdit={handleEditQuoteWithTab}
          />
          {showQuoteForm && isAdmin && (
            <QuoteForm
              quoteForm={quoteForm}
              customers={customers}
              inventory={inventory}
              categories={categories || []}
              onSave={handleCreateQuote}
              onCancel={() => {
                setShowQuoteForm(false);
                quoteForm.reset();
              }}
            />
          )}
        </>
      )}

      {/* NEW: Invoices Tab */}
      {activeTab === "invoices" && (
        <>
          {/* Invoice List Component */}
          <InvoiceList
            invoices={invoices}
            customers={customers}
            workOrders={workOrders}
            inventory={inventory}
            isAdmin={isAdmin}
            totalInvoiced={totalInvoiced}
            totalPaid={totalPaid}
            totalOutstanding={totalOutstanding}
            totalOverdue={totalOverdue}
            paidInvoices={paidInvoices}
            outstandingInvoices={outstandingInvoices}
            overdueInvoices={overdueInvoices}
            batchMode={batchMode}
            setBatchMode={setBatchMode}
            selectedInvoices={selectedInvoices}
            setSelectedInvoices={setSelectedInvoices}
            showInvoiceForm={showInvoiceForm}
            setShowInvoiceForm={setShowInvoiceForm}
            onOpenOverviewModal={openOverviewModal}
            onUpdateStatus={updateInvoiceStatus}
            onConvertToWorkOrder={convertInvoiceToWorkOrder}
            onClone={handleCloneInvoice}
            onDelete={deleteInvoice}
            onSendReminder={handleSendReminder}
            onEdit={handleEditInvoice}
            currentUser={currentUser}
            setInvoices={setInvoices}
            trackAction={trackAction}
          />

          {/* Invoice Statistics - REMOVED - Now in InvoiceList */}
          {false && (
            <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
              <button
                onClick={() => openOverviewModal("all")}
                className="bg-white rounded-lg shadow-md p-6 hover:shadow-xl transition-all transform hover:scale-105 cursor-pointer text-left"
              >
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-gray-600">Totaal Gefactureerd</p>
                    <p className="text-2xl font-bold text-blue-600 mt-1">
                      €{totalInvoiced.toFixed(2)}
                    </p>
                  </div>
                  <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                    <span className="text-2xl">🧾</span>
                  </div>
                </div>
              </button>

              <button
                onClick={() => openOverviewModal("paid")}
                className="bg-white rounded-lg shadow-md p-6 hover:shadow-xl transition-all transform hover:scale-105 cursor-pointer text-left"
              >
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-gray-600">Betaald</p>
                    <p className="text-2xl font-bold text-green-600 mt-1">
                      €{totalPaid.toFixed(2)}
                    </p>
                    <p className="text-xs text-gray-500 mt-1">
                      {paidInvoices.length} facturen
                    </p>
                  </div>
                  <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center">
                    <span className="text-2xl">✅</span>
                  </div>
                </div>
              </button>

              <button
                onClick={() => openOverviewModal("outstanding")}
                className="bg-white rounded-lg shadow-md p-6 hover:shadow-xl transition-all transform hover:scale-105 cursor-pointer text-left"
              >
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-gray-600">Uitstaand</p>
                    <p className="text-2xl font-bold text-yellow-600 mt-1">
                      €{totalOutstanding.toFixed(2)}
                    </p>
                    <p className="text-xs text-gray-500 mt-1">
                      {outstandingInvoices.length} facturen
                    </p>
                  </div>
                  <div className="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center">
                    <span className="text-2xl">⏳</span>
                  </div>
                </div>
              </button>

              <button
                onClick={() => openOverviewModal("overdue")}
                className="bg-white rounded-lg shadow-md p-6 hover:shadow-xl transition-all transform hover:scale-105 cursor-pointer text-left"
              >
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-gray-600">Verlopen</p>
                    <p className="text-2xl font-bold text-red-600 mt-1">
                      €{totalOverdue.toFixed(2)}
                    </p>
                    <p className="text-xs text-gray-500 mt-1">
                      {overdueInvoices.length} facturen
                    </p>
                  </div>
                  <div className="w-12 h-12 bg-red-100 rounded-lg flex items-center justify-center">
                    <span className="text-2xl">⚠️</span>
                  </div>
                </div>
              </button>
            </div>
          )}

          {/* Invoice Header - REMOVED - Now in InvoiceList */}
          {false && (
            <div className="flex items-center justify-between mb-6">
              <div className="text-sm text-gray-600">
                Totaal: {invoices.length} facturen
              </div>
              {isAdmin && (
                <button
                  onClick={() => setShowInvoiceForm(!showInvoiceForm)}
                  className="px-6 py-2 bg-primary text-white rounded-lg hover:bg-secondary transition-colors"
                >
                  + Nieuwe Factuur
                </button>
              )}
            </div>
          )}

          {/* Invoice Form Component */}
          {showInvoiceForm && isAdmin && (
            <InvoiceForm
              invoiceForm={invoiceForm}
              customers={customers}
              inventory={inventory}
              categories={categories || []}
              onSave={handleCreateInvoice}
              onCancel={() => {
                setShowInvoiceForm(false);
                invoiceForm.reset();
              }}
            />
          )}

          {/* Add Invoice Form - REMOVED - Now in InvoiceForm */}
          {/* Old invoice form code removed - now in InvoiceForm component */}

          {/* Invoice Form - REMOVED - Now in InvoiceForm component */}
          {/* Old invoice form code removed - now in InvoiceForm component */}

          {/* Invoices Header - Batch Operations - REMOVED - Now in InvoiceList */}
          {false && (
            <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
              <div className="text-sm text-gray-600">
                Totaal: {invoices.length} facturen
                {batchMode && selectedInvoices.length > 0 && (
                  <span className="ml-3 px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-xs font-semibold">
                    {selectedInvoices.length} geselecteerd
                  </span>
                )}
              </div>
              <div className="flex gap-2">
                {isAdmin && (
                  <>
                    <button
                      onClick={() => {
                        setBatchMode(!batchMode);
                        if (batchMode) {
                          setSelectedInvoices([]);
                        }
                      }}
                      className={`px-4 py-2 rounded-lg transition-colors ${
                        batchMode
                          ? "bg-blue-500 text-white"
                          : "bg-gray-200 text-gray-700 hover:bg-gray-300"
                      }`}
                    >
                      {batchMode ? "✓ Selectie Modus" : "☐ Batch Selectie"}
                    </button>
                    {batchMode && selectedInvoices.length > 0 && (
                      <div className="flex gap-2">
                        <button
                          onClick={() => {
                            // Bulk mark as paid
                            const unpaidInvoices = invoices.filter(
                              (inv) =>
                                selectedInvoices.includes(inv.id) &&
                                inv.status !== "paid"
                            );
                            if (unpaidInvoices.length === 0) {
                              alert("Geen onbetaalde facturen geselecteerd!");
                              return;
                            }
                            if (
                              confirm(
                                `Wil je ${unpaidInvoices.length} factuur(en) als betaald markeren?`
                              )
                            ) {
                              unpaidInvoices.forEach((inv) => {
                                const updatedInvoice = {
                                  ...inv,
                                  status: "paid" as const,
                                  paidDate: new Date()
                                    .toISOString()
                                    .split("T")[0],
                                  history: [
                                    ...(inv.history || []),
                                    {
                                      timestamp: new Date().toISOString(),
                                      action: "paid" as const,
                                      performedBy:
                                        currentUser.id || currentUser.name,
                                      details: `Status gewijzigd van ${inv.status} naar betaald`,
                                      fromStatus: inv.status,
                                      toStatus: "paid" as const,
                                    } as InvoiceHistoryEntry,
                                  ],
                                };
                                setInvoices(
                                  invoices.map((i) =>
                                    i.id === inv.id ? updatedInvoice : i
                                  )
                                );
                              });
                              setSelectedInvoices([]);
                              setBatchMode(false);
                            }
                          }}
                          className="px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors"
                        >
                          ✅ Markeer Betaald (
                          {
                            selectedInvoices.filter((id) => {
                              const inv = invoices.find((i) => i.id === id);
                              return inv?.status !== "paid";
                            }).length
                          }
                          )
                        </button>
                        <button
                          onClick={() => {
                            // Bulk send drafts
                            const draftInvoices = invoices.filter(
                              (inv) =>
                                selectedInvoices.includes(inv.id) &&
                                inv.status === "draft"
                            );
                            if (draftInvoices.length > 0) {
                              if (
                                confirm(
                                  `Wil je ${draftInvoices.length} concept factuur(en) verzenden?`
                                )
                              ) {
                                draftInvoices.forEach((inv) => {
                                  const updatedInvoice = {
                                    ...inv,
                                    status: "sent" as const,
                                    history: [
                                      ...(inv.history || []),
                                      {
                                        timestamp: new Date().toISOString(),
                                        action: "sent" as const,
                                        performedBy:
                                          currentUser.id || currentUser.name,
                                        details:
                                          "Status gewijzigd van concept naar verzonden",
                                        fromStatus: "draft" as const,
                                        toStatus: "sent" as const,
                                      } as InvoiceHistoryEntry,
                                    ],
                                  };
                                  setInvoices(
                                    invoices.map((i) =>
                                      i.id === inv.id ? updatedInvoice : i
                                    )
                                  );
                                  trackAction(
                                    currentUser.id || currentUser.name,
                                    currentUser.role || "user",
                                    ModuleKey.ACCOUNTING,
                                    "invoice_status_updated",
                                    "update",
                                    {
                                      invoiceId: inv.id,
                                      fromStatus: "draft",
                                      toStatus: "sent",
                                    }
                                  );
                                });
                                setSelectedInvoices([]);
                                setBatchMode(false);
                              }
                            }
                          }}
                          className="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
                        >
                          📤 Verzend (
                          {
                            selectedInvoices.filter((id) => {
                              const inv = invoices.find((i) => i.id === id);
                              return inv?.status === "draft";
                            }).length
                          }
                          )
                        </button>
                        <button
                          onClick={() => {
                            setSelectedInvoices([]);
                            setBatchMode(false);
                          }}
                          className="px-4 py-2 bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 transition-colors"
                        >
                          Annuleren
                        </button>
                      </div>
                    )}
                    <button
                      onClick={() => setShowInvoiceForm(!showInvoiceForm)}
                      className="px-6 py-2 bg-primary text-white rounded-lg hover:bg-secondary transition-colors"
                    >
                      + Nieuwe Factuur
                    </button>
                  </>
                )}
              </div>
            </div>
          )}

          {/* Invoices Grid - REMOVED - Now in InvoiceList */}
          {/* Old invoice grid code removed - now in InvoiceList component */}
        </>
      )}

      {/* Tip 4: Invoice Validation Modal - REMOVED - Now in InvoiceModals */}
      {/* Old invoice validation modal code removed - now in InvoiceModals component */}
    </div>
  );
};
