import React from "react";
import type {
  Invoice,
  Customer,
  WorkOrder,
  InventoryItem,
} from "../../../types";
import { ModuleKey } from "../../../types";
import {
  getCustomerName,
  getInvoiceStatusColor,
  getWorkOrderStatus,
  getWorkOrderBadge,
  isAutoGeneratedInvoice,
} from "../../../features/accounting/utils/helpers";
import { formatCurrency } from "../../../features/accounting/utils/formatters";
import { InvoiceItemRow } from "./InvoiceItemRow";
import { InvoiceActions } from "./InvoiceActions";

export interface InvoiceListProps {
  invoices: Invoice[];
  customers: Customer[];
  workOrders: WorkOrder[];
  inventory: InventoryItem[];
  isAdmin: boolean;
  // Statistics
  totalInvoiced: number;
  totalPaid: number;
  totalOutstanding: number;
  totalOverdue: number;
  paidInvoices: Invoice[];
  outstandingInvoices: Invoice[];
  overdueInvoices: Invoice[];
  // Batch mode
  batchMode: boolean;
  setBatchMode: (value: boolean) => void;
  selectedInvoices: string[];
  setSelectedInvoices: (value: string[] | ((prev: string[]) => string[])) => void;
  // Form visibility
  showInvoiceForm: boolean;
  setShowInvoiceForm: (value: boolean) => void;
  // Handlers
  onOpenOverviewModal: (type: "all" | "paid" | "outstanding" | "overdue") => void;
  onUpdateStatus: (invoiceId: string, status: Invoice["status"]) => void;
  onConvertToWorkOrder: (invoiceId: string) => void;
  onClone: (invoiceId: string) => void;
  onDelete: (invoiceId: string) => void;
  onSendReminder: (invoiceId: string, reminderNumber: 1 | 2) => void;
  onEdit?: (invoiceId: string) => void;
  currentUser: { id?: string; name: string; role?: string };
  setInvoices: React.Dispatch<React.SetStateAction<Invoice[]>>;
  trackAction?: (
    userId: string,
    userRole: string,
    module: string,
    action: string,
    type: string,
    metadata?: Record<string, any>
  ) => void;
}

export const InvoiceList: React.FC<InvoiceListProps> = ({
  invoices,
  customers,
  workOrders,
  inventory,
  isAdmin,
  totalInvoiced,
  totalPaid,
  totalOutstanding,
  totalOverdue,
  paidInvoices,
  outstandingInvoices,
  overdueInvoices,
  batchMode,
  setBatchMode,
  selectedInvoices,
  setSelectedInvoices,
  showInvoiceForm,
  setShowInvoiceForm,
  onOpenOverviewModal,
  onUpdateStatus,
  onConvertToWorkOrder,
  onClone,
  onDelete,
  onSendReminder,
  onEdit,
  currentUser,
  setInvoices,
  trackAction,
}) => {
  const handleBulkMarkAsPaid = () => {
    const unpaidInvoices = invoices.filter(
      (inv) =>
        selectedInvoices.includes(inv.id) &&
        inv.status !== "paid"
    );
    if (unpaidInvoices.length === 0) {
      alert("Geen onbetaalde facturen geselecteerd!");
      return;
    }
    if (
      confirm(
        `Wil je ${unpaidInvoices.length} factuur(en) als betaald markeren?`
      )
    ) {
      unpaidInvoices.forEach((inv) => {
        const updatedInvoice = {
          ...inv,
          status: "paid" as const,
          paidDate: new Date().toISOString().split("T")[0],
          history: [
            ...(inv.history || []),
            {
              timestamp: new Date().toISOString(),
              action: "paid" as const,
              performedBy: currentUser.id || currentUser.name,
              details: `Status gewijzigd van ${inv.status} naar betaald`,
              fromStatus: inv.status,
              toStatus: "paid" as const,
            },
          ],
        };
        setInvoices(
          invoices.map((i) =>
            i.id === inv.id ? updatedInvoice : i
          )
        );
      });
      setSelectedInvoices([]);
      setBatchMode(false);
    }
  };

  const handleBulkSend = () => {
    const draftInvoices = invoices.filter(
      (inv) =>
        selectedInvoices.includes(inv.id) &&
        inv.status === "draft"
    );
    if (draftInvoices.length > 0) {
      if (
        confirm(
          `Wil je ${draftInvoices.length} concept factuur(en) verzenden?`
        )
      ) {
        draftInvoices.forEach((inv) => {
          const updatedInvoice = {
            ...inv,
            status: "sent" as const,
            history: [
              ...(inv.history || []),
              {
                timestamp: new Date().toISOString(),
                action: "sent" as const,
                performedBy: currentUser.id || currentUser.name,
                details: "Status gewijzigd van concept naar verzonden",
                fromStatus: "draft" as const,
                toStatus: "sent" as const,
              },
            ],
          };
          setInvoices(
            invoices.map((i) =>
              i.id === inv.id ? updatedInvoice : i
            )
          );
          if (trackAction) {
            trackAction(
              currentUser.id || currentUser.name,
              currentUser.role || "user",
              ModuleKey.ACCOUNTING,
              "invoice_status_updated",
              "update",
              {
                invoiceId: inv.id,
                fromStatus: "draft",
                toStatus: "sent",
              }
            );
          }
        });
        setSelectedInvoices([]);
        setBatchMode(false);
      }
    }
  };

  return (
    <>
      {/* Invoice Statistics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <button
          onClick={() => onOpenOverviewModal("all")}
          className="bg-white rounded-lg shadow-md p-6 hover:shadow-xl transition-all transform hover:scale-105 cursor-pointer text-left"
        >
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Totaal Gefactureerd</p>
              <p className="text-2xl font-bold text-blue-600 mt-1">
                €{totalInvoiced.toFixed(2)}
              </p>
            </div>
            <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
              <span className="text-2xl">🧾</span>
            </div>
          </div>
        </button>

        <button
          onClick={() => onOpenOverviewModal("paid")}
          className="bg-white rounded-lg shadow-md p-6 hover:shadow-xl transition-all transform hover:scale-105 cursor-pointer text-left"
        >
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Betaald</p>
              <p className="text-2xl font-bold text-green-600 mt-1">
                €{totalPaid.toFixed(2)}
              </p>
              <p className="text-xs text-gray-500 mt-1">
                {paidInvoices.length} facturen
              </p>
            </div>
            <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center">
              <span className="text-2xl">✅</span>
            </div>
          </div>
        </button>

        <button
          onClick={() => onOpenOverviewModal("outstanding")}
          className="bg-white rounded-lg shadow-md p-6 hover:shadow-xl transition-all transform hover:scale-105 cursor-pointer text-left"
        >
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Uitstaand</p>
              <p className="text-2xl font-bold text-yellow-600 mt-1">
                €{totalOutstanding.toFixed(2)}
              </p>
              <p className="text-xs text-gray-500 mt-1">
                {outstandingInvoices.length} facturen
              </p>
            </div>
            <div className="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center">
              <span className="text-2xl">⏳</span>
            </div>
          </div>
        </button>

        <button
          onClick={() => onOpenOverviewModal("overdue")}
          className="bg-white rounded-lg shadow-md p-6 hover:shadow-xl transition-all transform hover:scale-105 cursor-pointer text-left"
        >
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Verlopen</p>
              <p className="text-2xl font-bold text-red-600 mt-1">
                €{totalOverdue.toFixed(2)}
              </p>
              <p className="text-xs text-gray-500 mt-1">
                {overdueInvoices.length} facturen
              </p>
            </div>
            <div className="w-12 h-12 bg-red-100 rounded-lg flex items-center justify-center">
              <span className="text-2xl">⚠️</span>
            </div>
          </div>
        </button>
      </div>

      {/* Invoices Header - Batch Operations */}
      <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
        <div className="text-sm text-gray-600">
          Totaal: {invoices.length} facturen
          {batchMode && selectedInvoices.length > 0 && (
            <span className="ml-3 px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-xs font-semibold">
              {selectedInvoices.length} geselecteerd
            </span>
          )}
        </div>
        <div className="flex gap-2">
          {isAdmin && (
            <>
              <button
                onClick={() => {
                  setBatchMode(!batchMode);
                  if (batchMode) {
                    setSelectedInvoices([]);
                  }
                }}
                className={`px-4 py-2 rounded-lg transition-colors ${
                  batchMode
                    ? "bg-blue-500 text-white"
                    : "bg-gray-200 text-gray-700 hover:bg-gray-300"
                }`}
              >
                {batchMode ? "✓ Selectie Modus" : "☐ Batch Selectie"}
              </button>
              {batchMode && selectedInvoices.length > 0 && (
                <div className="flex gap-2">
                  <button
                    onClick={handleBulkMarkAsPaid}
                    className="px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors"
                  >
                    ✅ Markeer Betaald (
                    {
                      selectedInvoices.filter((id) => {
                        const inv = invoices.find((i) => i.id === id);
                        return inv?.status !== "paid";
                      }).length
                    }
                    )
                  </button>
                  <button
                    onClick={handleBulkSend}
                    className="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
                  >
                    📤 Verzend (
                    {
                      selectedInvoices.filter((id) => {
                        const inv = invoices.find((i) => i.id === id);
                        return inv?.status === "draft";
                      }).length
                    }
                    )
                  </button>
                  <button
                    onClick={() => {
                      setSelectedInvoices([]);
                      setBatchMode(false);
                    }}
                    className="px-4 py-2 bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 transition-colors"
                  >
                    Annuleren
                  </button>
                </div>
              )}
              <button
                onClick={() => setShowInvoiceForm(!showInvoiceForm)}
                className="px-6 py-2 bg-primary text-white rounded-lg hover:bg-secondary transition-colors"
              >
                + Nieuwe Factuur
              </button>
            </>
          )}
        </div>
      </div>

      {/* Invoices Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {invoices
          .filter((invoice) => invoice.status !== "paid") // 🆕 V5.6: Verberg betaalde facturen (zichtbaar in Boekhouding & Dossier)
          .map((invoice) => {
            const workOrder = getWorkOrderStatus(
              invoice.workOrderId,
              workOrders
            );
            const workOrderBadge = getWorkOrderBadge(workOrder);
            const isCompleted = workOrder?.status === "Completed";
            const hasOverdue = invoice.status === "overdue";
            const isSelected = selectedInvoices.includes(invoice.id);

            return (
              <div
                key={invoice.id}
                className={`bg-white rounded-lg shadow-md p-6 transition-all ${
                  hasOverdue
                    ? "border-l-4 border-red-500"
                    : isCompleted
                    ? "border-l-4 border-green-500"
                    : ""
                } ${
                  batchMode && isSelected
                    ? "ring-4 ring-blue-500 border-blue-500"
                    : batchMode
                    ? "hover:ring-2 hover:ring-gray-300"
                    : ""
                }`}
              >
                <div className="flex items-start justify-between mb-4">
                  {batchMode && (
                    <div className="mr-3 mt-1">
                      <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={(e) => {
                          if (e.target.checked) {
                            setSelectedInvoices([
                              ...selectedInvoices,
                              invoice.id,
                            ]);
                          } else {
                            setSelectedInvoices(
                              selectedInvoices.filter(
                                (id) => id !== invoice.id
                              )
                            );
                          }
                        }}
                        className="w-5 h-5 text-blue-600 rounded focus:ring-blue-500"
                      />
                    </div>
                  )}
                  <div className="flex-1">
                    <h3 className="font-semibold text-lg text-neutral">
                      {invoice.invoiceNumber}
                    </h3>
                    <p className="text-sm text-gray-600">
                      {getCustomerName(invoice.customerId, customers)}
                    </p>
                    {invoice.quoteId && (
                      <p className="text-xs text-blue-600 mt-1">
                        Van offerte: {invoice.quoteId}
                      </p>
                    )}
                    {workOrderBadge && (
                      <button
                        onClick={() => {
                          alert(`Werkorder ID: ${invoice.workOrderId}`);
                        }}
                        className={`mt-2 px-3 py-1 rounded-full text-xs font-semibold border-2 ${workOrderBadge.color} hover:opacity-80 transition-opacity cursor-pointer`}
                        title="Klik om naar werkorder te gaan"
                      >
                        {workOrderBadge.icon} {workOrderBadge.text}
                      </button>
                    )}
                  </div>
                  <span
                    className={`px-3 py-1 rounded-full text-xs font-semibold ${getInvoiceStatusColor(
                      invoice.status
                    )}`}
                  >
                    {invoice.status === "draft" && "Concept"}
                    {invoice.status === "sent" && "Verzonden"}
                    {invoice.status === "paid" && "Betaald"}
                    {invoice.status === "overdue" && "Verlopen"}
                    {invoice.status === "cancelled" && "Geannuleerd"}
                  </span>
                </div>

                    {/* Items */}
                    <div className="space-y-2 mb-3">
                      <h4 className="text-sm font-semibold text-gray-700">
                        Items:
                      </h4>
                      {invoice.items.map((item, index) => (
                        <InvoiceItemRow
                          key={index}
                          item={item}
                          index={index}
                          inventory={inventory}
                          mode="display"
                        />
                      ))}
                    </div>

                {/* Labor */}
                {invoice.labor && invoice.labor.length > 0 && (
                  <div className="space-y-2 mb-3 border-t pt-3">
                    <h4 className="text-sm font-semibold text-gray-700">
                      Werkuren:
                    </h4>
                    {invoice.labor.map((labor, index) => (
                      <div
                        key={index}
                        className="flex justify-between text-sm"
                      >
                        <span className="text-gray-700">
                          {labor.description}
                          <span className="text-gray-500">
                            {" "}
                            ({labor.hours}u @ €{labor.hourlyRate}/u)
                          </span>
                        </span>
                        <span className="font-medium">
                          €{labor.total.toFixed(2)}
                        </span>
                      </div>
                    ))}
                  </div>
                )}

                {/* Totals */}
                <div className="border-t pt-3 mb-4 space-y-1">
                  <div className="flex justify-between text-sm text-gray-600">
                    <span>Subtotaal (excl. BTW):</span>
                    <span>€{invoice.subtotal.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between text-sm text-gray-600">
                    <span>BTW ({invoice.vatRate}%):</span>
                    <span>€{invoice.vatAmount.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between items-center pt-2 border-t">
                    <span className="font-semibold text-neutral">
                      Totaal (incl. BTW):
                    </span>
                    <span className="text-xl font-bold text-primary">
                      €{invoice.total.toFixed(2)}
                    </span>
                  </div>
                </div>

                <div className="flex justify-between text-sm text-gray-600 mb-4">
                  <span>Factuurdatum: {invoice.issueDate}</span>
                  <span>Vervaldatum: {invoice.dueDate}</span>
                </div>

                {/* 🆕 V5.6: Reminder Information */}
                {invoice.reminders && invoice.status === "sent" && (
                  <div className="p-3 bg-blue-50 rounded-lg mb-4 border-l-4 border-blue-400">
                    <h4 className="text-sm font-semibold text-blue-800 mb-2">
                      📅 Herinneringsplanning
                    </h4>
                    <div className="space-y-2">
                      {invoice.reminders.reminder1Date && (
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-blue-700">
                            Herinnering 1:{" "}
                            {new Date(
                              invoice.reminders.reminder1Date
                            ).toLocaleDateString("nl-NL")}
                          </span>
                          {invoice.reminders.reminder1Sent ? (
                            <span className="px-2 py-1 bg-green-100 text-green-800 rounded-full text-xs font-semibold">
                              ✓ Verzonden{" "}
                              {invoice.reminders.reminder1SentDate
                                ? new Date(
                                    invoice.reminders.reminder1SentDate
                                  ).toLocaleDateString("nl-NL")
                                : ""}
                            </span>
                          ) : (
                            <button
                              onClick={() =>
                                onSendReminder(invoice.id, 1)
                              }
                              className="px-2 py-1 bg-blue-500 text-white rounded hover:bg-blue-600 text-xs font-semibold transition-colors"
                            >
                              📧 Herinnering nu sturen
                            </button>
                          )}
                        </div>
                      )}
                      {invoice.reminders.reminder2Date && (
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-blue-700">
                            Herinnering 2:{" "}
                            {new Date(
                              invoice.reminders.reminder2Date
                            ).toLocaleDateString("nl-NL")}
                          </span>
                          {invoice.reminders.reminder2Sent ? (
                            <span className="px-2 py-1 bg-green-100 text-green-800 rounded-full text-xs font-semibold">
                              ✓ Verzonden{" "}
                              {invoice.reminders.reminder2SentDate
                                ? new Date(
                                    invoice.reminders.reminder2SentDate
                                  ).toLocaleDateString("nl-NL")
                                : ""}
                            </span>
                          ) : (
                            <button
                              onClick={() =>
                                onSendReminder(invoice.id, 2)
                              }
                              className="px-2 py-1 bg-blue-500 text-white rounded hover:bg-blue-600 text-xs font-semibold transition-colors"
                            >
                              📧 Herinnering nu sturen
                            </button>
                          )}
                        </div>
                      )}
                    </div>
                    <p className="text-xs text-blue-600 mt-2">
                      💡 Template: "Betreft factuur {invoice.invoiceNumber}{" "}
                      – vriendelijke herinnering"
                    </p>
                  </div>
                )}

                {invoice.paidDate && (
                  <div className="p-3 bg-green-50 rounded-lg mb-4">
                    <p className="text-sm text-green-700 font-medium">
                      ✓ Betaald op: {invoice.paidDate}
                    </p>
                  </div>
                )}

                {invoice.paymentTerms && (
                  <div className="text-xs text-gray-500 mb-4">
                    Betalingstermijn: {invoice.paymentTerms}
                  </div>
                )}

                {invoice.notes && (
                  <div className="p-3 bg-gray-50 rounded-lg mb-4">
                    <p className="text-sm text-gray-700">{invoice.notes}</p>
                  </div>
                )}

                {/* Tip 4: Warning banner for auto-generated invoices */}
                {invoice.status === "draft" &&
                  isAutoGeneratedInvoice(invoice) && (
                    <div className="p-4 bg-yellow-50 rounded-lg mb-4 border-l-4 border-yellow-400">
                      <div className="flex items-start gap-3">
                        <svg
                          className="w-6 h-6 text-yellow-600 flex-shrink-0 mt-0.5"
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={2}
                            d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
                          />
                        </svg>
                        <div className="flex-1">
                          <h4 className="text-sm font-semibold text-yellow-800 mb-1">
                            ⚠️ Automatisch aangemaakte factuur
                          </h4>
                          <p className="text-xs text-yellow-700 mb-2">
                            Deze factuur is automatisch aangemaakt na
                            voltooiing van een werkorder. Controleer{" "}
                            <strong>gewerkte uren</strong>,{" "}
                            <strong>materialen</strong> en voeg eventueel{" "}
                            <strong>meerwerk</strong> toe voordat u
                            verzendt.
                          </p>
                          {workOrder && (
                            <div className="mt-2 text-xs">
                              <button
                                onClick={() => onEdit && onEdit(invoice.id)}
                                className="text-yellow-800 underline hover:text-yellow-900 font-medium"
                              >
                                ✏️ Bewerk factuur om te controleren
                              </button>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  )}

                {/* Work Order Status Info for Completed */}
                {isCompleted && workOrder && (
                  <div className="p-3 bg-green-50 rounded-lg mb-4 border border-green-200">
                    <div className="flex items-center gap-2 mb-2">
                      <svg
                        className="w-5 h-5 text-green-600"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                        />
                      </svg>
                      <span className="text-sm font-semibold text-green-700">
                        Werkorder Voltooid
                      </span>
                    </div>
                    {workOrder.hoursSpent !== undefined &&
                      workOrder.estimatedHours && (
                        <p className="text-xs text-gray-700">
                          ⏱️ Gewerkt: {workOrder.hoursSpent}u (Geschat:{" "}
                          {workOrder.estimatedHours}u)
                          {workOrder.hoursSpent !==
                            workOrder.estimatedHours && (
                            <span
                              className={`ml-2 font-semibold ${
                                workOrder.hoursSpent <=
                                workOrder.estimatedHours * 1.1
                                  ? "text-green-600"
                                  : workOrder.hoursSpent <=
                                    workOrder.estimatedHours * 1.25
                                  ? "text-orange-600"
                                  : "text-red-600"
                              }`}
                            >
                              (
                              {Math.round(
                                (workOrder.hoursSpent /
                                  workOrder.estimatedHours) *
                                  100
                              )}
                              %)
                            </span>
                          )}
                        </p>
                      )}
                  </div>
                )}

                {/* Editable notification for active workorders */}
                {invoice.workOrderId &&
                  workOrder &&
                  workOrder.status !== "Completed" &&
                  isAdmin && (
                    <div className="p-3 bg-blue-50 rounded-lg mb-4 border border-blue-200">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <svg
                            className="w-5 h-5 text-blue-600"
                            fill="none"
                            stroke="currentColor"
                            viewBox="0 0 24 24"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeWidth={2}
                              d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                            />
                          </svg>
                          <span className="text-xs font-medium text-blue-800">
                            ✏️ Deze factuur is gekoppeld aan een actieve
                            werkorder. Wijzigingen worden automatisch
                            gesynchroniseerd.
                          </span>
                        </div>
                      </div>
                    </div>
                  )}

                {/* Action Buttons */}
                <InvoiceActions
                  invoice={invoice}
                  isAdmin={isAdmin}
                  onUpdateStatus={onUpdateStatus}
                  onConvertToWorkOrder={onConvertToWorkOrder}
                  onClone={onClone}
                  onDelete={onDelete}
                  onEdit={onEdit}
                />
              </div>
            );
          })}
      </div>

      {invoices.filter((invoice) => invoice.status !== "paid").length ===
        0 && (
        <div className="text-center py-12">
          <p className="text-gray-500 text-lg mb-2">
            Geen openstaande facturen
          </p>
          <p className="text-sm text-gray-400">
            Betaalde facturen zijn verplaatst naar{" "}
            <span className="font-semibold text-primary">
              Boekhouding & Dossier
            </span>
          </p>
        </div>
      )}
    </>
  );
};

