// features/accounting/hooks/useInvoiceValidation.ts - Refactored < 200 lines
import { useCallback } from 'react';
import type { Invoice, Employee, User, ModuleKey, InvoiceHistoryEntry } from '../../../types';
import { trackAction } from '../../../utils/analytics';
import { shouldShowValidationModal } from '../services/invoiceService';
import { isAutoGeneratedInvoice, createHistoryEntry, getEmployeeName } from '../utils/helpers';

/**
 * Hook for invoice validation workflow
 * Handles validation modal and status confirmation
 */
export const useInvoiceValidation = (
  invoices: Invoice[],
  setInvoices: React.Dispatch<React.SetStateAction<Invoice[]>>,
  currentUser: User,
  employees: Employee[],
  invoiceToValidate: Invoice | null,
  setShowInvoiceValidationModal: (show: boolean) => void,
  setInvoiceToValidate: (invoice: Invoice | null) => void,
  resetValidation: () => void
) => {
  /**
   * Confirm invoice validation
   */
  const confirmInvoiceValidation = useCallback(() => {
    if (!invoiceToValidate) return;

    const invoice = invoiceToValidate;
    const now = new Date().toISOString();
    const oldStatus = invoice.status;

    // Check if validation modal should be shown
    if (shouldShowValidationModal(invoice)) {
      setShowInvoiceValidationModal(true);
      return;
    }

    // Update invoice status
    const updates: Partial<Invoice> = {
      status: 'sent' as const,
      history: [
        ...(invoice.history || []),
        createHistoryEntry(
          'invoice',
          'sent',
          `Status gewijzigd van "${oldStatus}" naar "sent" na validatie door ${getEmployeeName(
            currentUser.employeeId,
            employees
          )}`,
          currentUser,
          { fromStatus: oldStatus, toStatus: 'sent' }
        ) as InvoiceHistoryEntry,
      ],
    };

    // Update timestamps
    if (!invoice.timestamps) {
      updates.timestamps = { created: invoice.issueDate };
    } else {
      updates.timestamps = { ...invoice.timestamps };
    }

    if (!updates.timestamps?.sent) {
      updates.timestamps = {
        ...updates.timestamps,
        sent: now,
      };

      // Automatische herinneringsplanning bij verzenden
      if (invoice.dueDate) {
        const dueDate = new Date(invoice.dueDate);
        const reminder1Date = new Date(dueDate);
        reminder1Date.setDate(dueDate.getDate() + 7); // +7 dagen na vervaldatum

        const reminder2Date = new Date(dueDate);
        reminder2Date.setDate(dueDate.getDate() + 14); // +14 dagen na vervaldatum

        updates.reminders = {
          reminder1Date: reminder1Date.toISOString().split('T')[0],
          reminder1Sent: false,
          reminder2Date: reminder2Date.toISOString().split('T')[0],
          reminder2Sent: false,
        };
      }

      // Track invoice validation completion
      trackAction(currentUser.employeeId, currentUser.role, ModuleKey.ACCOUNTING, 'validate_invoice', 'complete', {
        invoiceId: invoice.id,
        invoiceNumber: invoice.invoiceNumber,
        wasAutoGenerated: isAutoGeneratedInvoice(invoice),
      });
    }

    // Update invoice in state
    setInvoices(invoices.map((inv) => (inv.id === invoice.id ? { ...inv, ...updates } : inv)));

    // Close modal and reset
    resetValidation();

    // Show success message
    alert(`✅ Factuur ${invoice.invoiceNumber} succesvol gevalideerd en verzonden!`);
  }, [invoiceToValidate, invoices, currentUser, employees, setInvoices, setShowInvoiceValidationModal, resetValidation]);

  return {
    confirmInvoiceValidation,
  };
};
